### ISSUE TITLE
Table component not passing 'key' prop to children of lists

### ISSUE THREAD

**Issue by Klaas058** [daisyui/react-daisyui#207]
Component: Table
Issue: Table component not passing 'key' prop to children of lists

Currently the Table component is not passing the 'key' prop to its children that are returned by the array.map in Row, Footer and Head component.
This is causing client side warnings and possibly unnecessary rerenders of the children.

I've already written the fix for it but I do not have the rights to open a branch and push to this repository.
I could not find contributing guidelines but I'd be happy to contribute to this.

**Comment by benjitrosch** [comment]
Hi @Klaas058,

Thank you for helping out, would be happy to accept the contribution!

In order to open a PR on an Open Source project on GitHub, you first click `Fork` in the upper-right corner. This will create a copy of the repo on your account. Then, from your copy, you can open a pull request against the main branch of the original repo. I recommend to follow this guide for making contributions: https://github.com/firstcontributions/first-contributions.

If you've likely already cloned it and the remote origin is set to the `daisyui` copy, simply use `git remote remove origin` and then `git remote add origin [[ YOUR FORKED REPO HERE ]]`.

**Comment by Klaas058** [comment]
Hi @benjitrosch,

Thanks for the reply, you've spotted a first time contributor to open source, thank you for showing me the steps!
I've opened a pull request against main like you said, I will watch if any issues or feedback arise.

Thanks again and happy to help :)

**Comment by benjitrosch** [comment]
Happy to help, thanks for contributing! I should be able to review the PR soon!
