### ISSUE TITLE
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>

### ISSUE THREAD

**Issue by mattiaz9** [daisyui/react-daisyui#223]
I got this warning from webpack:
```
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

**Comment by Klaas058** [comment]
Hi @mattiaz9!

Thank you for opening the issue, you are right, I see the issue warning too when using the Select component.

I believe the issue is similar to the issue in #215 (proposal for a fix in #222) where the `value` prop is part of the [controlled](https://reactjs.org/docs/forms.html#controlled-components) component by React and the `selected` prop is part of the [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) 'normal' html component.

When given a value the `selected` state of the `option` should be controlled by the `select` not the `option` itself.

I will create a PR to fix this shortly.
