### ISSUE TITLE
[4.0.1]: New Modal causes reflow issues

### ISSUE THREAD

**Issue by exoRift** [daisyui/react-daisyui#398]
The new `Modal` component (this even affects the legacy component as well) blocks scrolling behind the backdrop. However, this also removes the page's scrollbar, causing the page to shift whenever a modal is opened.

**Comment by benjitrosch** [comment]
@exoRift the modal stopping the user from scrolling is intentional and part of the design system. However, I can't say I've seen what you're describing, can you post an example?

**Comment by exoRift** [comment]
If you're on a page that's long enough to have a scrollbar, opening a Modal will remove the page's scrollbar, causing a slight shift to the right (because the page fills the scrollbar space)

**Comment by benjitrosch** [comment]
@exoRift sorry for not responding sooner, thought I had responded already but today I saw the issue was still open.

This isn't an issue with the library but rather the intended behavior. Please see this commit: https://github.com/saadeghi/daisyui/commit/4ba3d4cd2da679a4a24348c4d76afa480b181122

It is possible to override this style from your own CSS if you'd like but it's not an option I'll be introducing to the library.
