### ISSUE TITLE
Swap.onClick fires twice

### ISSUE THREAD

**Issue by PolarizedIons** [daisyui/react-daisyui#421]
Example: Click on the swap element. Look at the count increasing by 2 every time

https://codesandbox.io/p/sandbox/little-water-vj2zxt

**Comment by benjitrosch** [comment]
@PolarizedIons it's working for me from the CodeSandbox you provided with no changes. What are you seeing, do you mind recording?

Here's what I get from the link you sent:


https://github.com/daisyui/react-daisyui/assets/64439681/519e106a-9b45-41bf-abea-085a960f7ecd

**Comment by PolarizedIons** [comment]
Huh... It should look something like this. I'm not at my pc for a bit though, I'll try get a recording then if it doesn't work for you by then 
![Screenshot_20230923-191816](https://github.com/daisyui/react-daisyui/assets/4587682/46a239b7-de28-4cd5-b86c-49718843ae26)

**Comment by PolarizedIons** [comment]
https://github.com/daisyui/react-daisyui/assets/4587682/c978d1bd-bbb1-4b6f-8841-b85e6f0b5b58

**Comment by PolarizedIons** [comment]
did you manage to replicate it, @benjitrosch ?

**Comment by benjitrosch** [comment]
@PolarizedIons I was able to reproduce it locally! The issue was due to the way the `<Swap>` component is built, using an outer `<label>` and an inner `<input type="checkbox">`. Basically, the `onClick` would fire once for the label and then propagate to the input.

To fix it, I've just re-typed the `onClick` (and `onChange`) event for the input only. Here's the commit: 6478b1bd690719deaa89cf5ccc7a8ead43996b4b

Thanks for finding this! Not sure what was going on with the Codesandbox 👀
